# Generated by Django 4.1.9 on 2023-07-26 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('victim', models.CharField(max_length=100)),
                ('crime_date', models.CharField(max_length=30)),
                ('report_date', models.CharField(default=datetime.datetime(2023, 7, 26, 16, 56, 29, 914278), max_length=100)),
            ],
        ),
    ]
