# Generated by Django 4.1.9 on 2023-07-26 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPTS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime_reports',
            name='case_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crime_reports',
            name='case_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crime_reports',
            name='case_withdraw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crime_reports',
            name='report_date',
            field=models.CharField(default=datetime.datetime(2023, 7, 26, 17, 21, 54, 964261), max_length=100),
        ),
    ]
