# Generated by Django 4.1.9 on 2023-07-26 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPTS_App', '0002_crime_reports_case_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime_reports',
            name='status',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='crime_reports',
            name='report_date',
            field=models.CharField(default=datetime.datetime(2023, 7, 26, 21, 3, 32, 553713), max_length=100),
        ),
    ]
