# Generated by Django 4.1.9 on 2023-07-26 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPTS_App', '0003_crime_reports_status_alter_crime_reports_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime_reports',
            name='case_completed',
        ),
        migrations.RemoveField(
            model_name='crime_reports',
            name='case_pending',
        ),
        migrations.RemoveField(
            model_name='crime_reports',
            name='case_withdraw',
        ),
        migrations.AlterField(
            model_name='crime_reports',
            name='report_date',
            field=models.CharField(default=datetime.datetime(2023, 7, 26, 21, 27, 23, 485813), max_length=100),
        ),
    ]
