# Generated by Django 4.1.9 on 2023-07-26 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPTS_App', '0004_remove_crime_reports_case_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('image', models.ImageField(upload_to='FIR_Files')),
                ('upload_date', models.CharField(default=datetime.datetime(2023, 7, 26, 22, 58, 3, 993640), max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='crime_reports',
            name='report_date',
            field=models.CharField(default=datetime.datetime(2023, 7, 26, 22, 58, 3, 992670), max_length=100),
        ),
    ]
