# Generated by Django 4.1.9 on 2023-08-04 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPTS_App', '0005_fir_alter_crime_reports_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_reports',
            name='report_date',
            field=models.CharField(default=datetime.datetime(2023, 8, 4, 19, 46, 38, 340908), max_length=100),
        ),
        migrations.AlterField(
            model_name='fir',
            name='upload_date',
            field=models.CharField(default=datetime.datetime(2023, 8, 4, 19, 46, 38, 340908), max_length=100),
        ),
    ]
